apiVersion: v1
kind: Service
metadata:
  name: register-app-service
  labels:
    app: register-app 
spec:
  selector:
    app: register-app

  ports:
    - port: 3000
      targetPort: 3000

  type: LoadBalancer
